# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CRSguesser
                                 A QGIS plugin
 Guesses unknown CRS for layers
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-08-05
        copyright            : (C) 2021 by Brigit Danthine
        email                : brigit.danthine@uibk.ac.at
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load CRSguesser class from file CRSguesser.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .crs_guesser import CRSguesser
    return CRSguesser(iface)
